# Cloud Run service configuration
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: misinformation-detector
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cpu-boost: "true"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/memory: "2Gi"
        run.googleapis.com/cpu: "1"
        run.googleapis.com/max-scale: "10"
        run.googleapis.com/min-scale: "0"
    spec:
      containerConcurrency: 10
      timeoutSeconds: 300
      serviceAccountName: PROJECT_ID-compute@developer.gserviceaccount.com
      containers:
      - image: gcr.io/PROJECT_ID/misinformation-detector:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: api-key
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: news-api-key
              key: api-key
        - name: FLASK_ENV
          value: production
        - name: PORT
          value: "8080"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        startupProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
          failureThreshold: 3
  traffic:
  - percent: 100
    latestRevision: true
